#!/usr/bin/env bash

# For disabling single_click_activate in Qt 5.
# Including VLC.
qt5_plat()
{
    # export QT_QPA_PLATFORMTHEME=lxqt
    true
}

# DEFAULT_DESK="kde4"
DEFAULT_DESK="kde5"
# DEFAULT_DESK="e"
DEFAULT_DESK="xfce"
# DEFAULT_DESK="sawfish"
# DEFAULT_DESK="wmaker"
# DEFAULT_DESK="gnome"

if test -e /etc/fedora-release
then
    export NO_AT_BRIDGE=1
    isfedora=1
fi
WHICH_DESK="${WD:-${DEFAULT_DESK}}"

if false ; then
    true
elif [ "$WHICH_DESK" = "awe" ] ; then
    exec awesome
elif [ "$WHICH_DESK" = "cin" ] ; then
    exec cinnamon-session
elif [ "$WHICH_DESK" = "compiz" ] ; then
    fusion-icon &
elif [ "$WHICH_DESK" = "e" ] ; then
    exec enlightenment_start
elif [ "$WHICH_DESK" = "fluxbox" ] ; then
    exec startfluxbox
elif [ "$WHICH_DESK" = "fvwm" ] ; then
    # exec fvwm-themes-start -e fvwm2
    fvwm2
elif [ "$WHICH_DESK" = "gnome" ] ; then
    if test -n "$isfedora"
    then
        gnome-session
    else
        exec startgnome
    fi
elif [ "$WHICH_DESK" = "gnome-trace" ] ; then
    strace -f -o "$HOME/gnome.strace" startgnome
elif [ "$WHICH_DESK" = "i3" ] ; then
    i3
elif [ "$WHICH_DESK" = "icewm" ] ; then
    if test -n "$isfedora"
    then
        icewm
    else
        starticewm
    fi
elif [ "$WHICH_DESK" = "icewm-trace" ] ; then
    strace -f -o "$HOME/icewm.strace" starticewm
elif [ "$WHICH_DESK" = "jwm" ] ; then
    # qt5_plat
    PATH="/opt/shlomif/jwm/bin:$PATH"
    exec jwm
elif [ "$WHICH_DESK" = "kde4" ] ; then
    # qt5_plat
    exec startkde
elif [ "$WHICH_DESK" = "kde5" ] ; then
    # ( startplasma-x11 ) |& tee -a ~/k5.txt
    startplasma-x11
    # exec dbus-launch --exit-with-session startkde
    # strace -f -o ~/k.strace dbus-launch --exit-with-session startkde
    # startkde
elif [ "$WHICH_DESK" = "kde6" ] ; then
    # ( startplasma ) |& tee -a ~/k5.txt
    startplasma
elif [ "$WHICH_DESK" = "lxde" ] ; then
    exec startlxde
elif [ "$WHICH_DESK" = "lxqt" ] ; then
    exec startlxqt
elif [ "$WHICH_DESK" = "mate" ] ; then
    exec startmate
elif [ "$WHICH_DESK" = "nimdow" ] ; then
    (
        set -e -x
        if false
        then
            cd ~/Download/unpack/to-del/Nim
            PATH="$PWD/bin:$PATH"
            cd ~/Download/unpack/to-del/nimdow
            PATH="$PWD/bin:$PATH"
            nimdow # ./config.toml
        fi
        ~/Download/unpack/to-del/nimdow/bin/nimdow
    )
elif [ "$WHICH_DESK" = "razor" ] ; then
    exec startrazor
elif [ "$WHICH_DESK" = "sawfish" ] ; then
    exec startsawfish
elif [ "$WHICH_DESK" = "tde" ] ; then
    exec /opt/trinity/bin/starttde
elif [ "$WHICH_DESK" = "wmaker" ] ; then
    exec startwindowmaker
elif [ "$WHICH_DESK" = "xfce" ] ; then
    # qt5_plat
    exec startxfce4
elif [ "$WHICH_DESK" = "xfce-trace" ] ; then
    strace -f -o "$HOME"/xfce4.strace startxfce4
fi
