#!/usr/bin/perl

use strict;
use warnings;

my $HOME = '/home/shlomif';

my $SRC_DIR = "$HOME/progs/freecell/git/fc-solve/fc-solve/source";
my $FCS_PGO_THEME = $ENV{FCS_PGO_THEME};
# Validate FCS_PGO_THEME
if ($FCS_PGO_THEME !~ m#\A(?:-l [A-Za-z0-9_]+)|(?:--read-from-file [0-9]+,[/A-Za-z0-9_\-\.]+)#)
{
    die "Wrong FCS_PGO_THEME!";
}
my $SUDO_USER = $ENV{SUDO_USER};
print( "USER=$SUDO_USER\n");
exec(qw#sudo nice -n-20 ionice -c1 -n0 sudo -u#, $SUDO_USER , qw#bash -c#, qq#SRC_DIR=\"$SRC_DIR\" FCS_PGO_THEME="$FCS_PGO_THEME" bash ~/bin/fcs-bench.bash 8#,);
