#!/bin/bash

conf_dir="$(cd "$(dirname "$0")" && pwd)"

dot_vim="$HOME/.vim"
if ! test -e "$dot_vim" ; then
  ln -s "$conf_dir/dot-vim" "$dot_vim"
fi
(
    cd "$dot_vim"
    if ! test -d "vim-addon-manager" ; then
	git clone 'https://github.com/MarcWeber/vim-addon-manager.git'
    fi
    if ! test -d "vim-addon-manager-known-repositories"; then
        git clone 'git://github.com/MarcWeber/vim-addon-manager-known-repositories.git'
    fi
)

conf_vim_dir="$HOME/conf/Vim"
if ! test -e "$conf_vim_dir" ; then
  mkdir -p "$(dirname "$conf_vim_dir")"
  ln -s "$conf_dir/conf-Vim" "$conf_vim_dir"
fi
