#!/usr/bin/env bash

conf_dir="$(cd "$(dirname "$0")" && pwd)"

dot_vim="$HOME/.vim"
(
    cd "$dot_vim"
    if ! test -d "vim-addon-manager" ; then
	git clone 'https://github.com/MarcWeber/vim-addon-manager.git'
    fi
    if ! test -d "vim-addon-manager-known-repositories"; then
        git clone 'git://github.com/MarcWeber/vim-addon-manager-known-repositories.git'
    fi
)

conf_vim_dir="$HOME/conf/Vim"

vimrc="$HOME/.vimrc"
conf="$HOME/.config"
nvim="$conf/nvim"
extbase=ExtraUltiSnips
ext="$nvim/$extbase"
if ! test -e "$ext"
then
    ln -s "$HOME/.vim/$extbase" "$ext"
fi
