#!/usr/bin/env perl

use strict;
use warnings;
use autodie;

use File::Spec ();
use File::Basename qw/ dirname /;
use File::Path qw(mkpath);

my $conf_dir = File::Spec->rel2abs( dirname($0) );
my $h        = $ENV{HOME};

my $rel_path = $conf_dir;
$rel_path =~ s{\A\Q$h/conf\E/}{../};

mkpath( ["$h/conf/Bash"] );
my $THEMES_DIR      = "$rel_path/Themes";
my $THEMES_DIR_LINK = "$h/conf/Bash/Themes";
if ( !-l $THEMES_DIR_LINK )
{
    symlink( $THEMES_DIR, $THEMES_DIR_LINK );
}
eval { rename( "$h/.bashrc", "$h/.bashrc.orig" ); };
symlink( "$h/conf/trunk/shlomif-settings/Bash/bashrc/rc.bash", "$h/.bashrc" );
eval { rename( "$h/.zshrc", "$h/.zshrc.orig" ); };
symlink( "$h/conf/trunk/shlomif-settings/Bash/bashrc/rc.zsh", "$h/.zshrc" );
system(qq#cd "$THEMES_DIR_LINK" && ./gen_list.sh#);
