#!/usr/bin/env bash

conf_dir="$(cd "$(dirname "$0")" && pwd)"

gitconf="$HOME/.gitconfig"
if ! test -e "$gitconf" ; then
    ln -s "$conf_dir/.gitconfig" "$gitconf"
fi

conf_git="$HOME/conf/git"
if ! test -e "$conf_git" ; then
    ln -s "$conf_dir/conf-git" "$conf_git"
fi
