#!/bin/bash

# For GNU screen to use a different key-binding
alias screen='screen -e "^^6"'

_sys()
{
    echo "$@"
    "$@"
}

u()
{
    local common_args
    common_args="--auto --keep --resume --noclean --downloader wget --wget-options -c"
    ( cd $HOME ;
    if test "$#" -eq 0 ; then
        _sys urpmi $common_args --auto-select;
    else
        _sys urpmi $common_args "$@" ;
    fi
    )
}

uu()
{
    (cd $HOME ; urpmi.update -a)
}

wu()
{
    while ! u ; do true ; done
}

up()
{
    urpmi --auto $(perlmf as_rpm_colon "$@")
}

function _cpan_d_format()
{
    (
    if test -e /etc/mageia-release ; then
        echo "CPANPLUS::Dist::Mageia"
    else
        echo "CPANPLUS::Dist::Mdv"
    fi
    )
}

function c()
{ 
    cpan2dist --verbose --format="$(_cpan_d_format)" \
        --defaults --install --timeout 0 $(perlmf as_colon "$@")
}

function qp()
{ 
    local pm="$1"
    shift

    urpmq --whatprovides "$(perlmf as_rpm_colon "$pm")" ; 
}

function cp_to_shlomif()
{
    local dest
    dest=~shlomif/progs/Rpms/SRPMS/
    cp -f /root/rpmbuild/SRPMS/*.src.rpm "$dest" ; 
    chown shlomif.shlomif "$dest"/*.src.rpm
}

function pap()
{
    apt-get install $(perlmf as_deb "$@");
}

e()
{
    urpme "$@"
}

# urpme orphans.
eo()
{
    e --auto-orphans
}

alias q='urpmq --fuzzy -a'
