#!/bin/bash

# For GNU screen to use a different key-binding
alias screen='screen -e "^^6"'

u()
{
    ( cd $HOME ; urpmi --auto --auto-select --keep --resume --noclean )
}

uu()
{
    (cd $HOME ; urpmi.update -a)
}

wu()
{
    while ! u ; do true ; done
}

function normalize_perlmod()
{
    local pm="$1"
    shift

    echo "$pm" | perl -p -e 's/perl-//; s{[-/]}{::}g; s{\.pm(\n?)\z}{$1}'
}

function rpmize_perlmod()
{
    local pm="$1"
    shift
    echo "perl($(normalize_perlmod "$pm"))"
}

function up()
{ 
    local pm="$1"
    shift

    urpmi --auto "$(rpmize_perlmod "$pm")"
}

function c()
{ 
    local pm="$1"
    shift

    cpan2dist --verbose --format=CPANPLUS::Dist::Mdv \
        --install --timeout 0 "$(normalize_perlmod "$pm")" ; 
}

function qp()
{ 
    local pm="$1"
    shift

    urpmq --whatprovides "$(rpmize_perlmod "$pm")" ; 
}

function cp_to_shlomi()
{
    local dest
    dest=~shlomi/progs/Rpms/SRPMS/
    cp -f /root/rpmbuild/SRPMS/*.src.rpm "$dest" ; 
    chown shlomi.shlomi "$dest"/*.src.rpm
}
