#!/usr/bin/env perl

use autodie;
use strict;
use warnings;

use File::Spec;
use File::Basename;
use File::Path qw(mkpath);

my $conf_dir = File::Spec->rel2abs( dirname($0) );
my $h        = $ENV{HOME};

my $rel_path = $conf_dir;
$rel_path =~ s{\A\Q$h/conf\E/}{../};

symlink( "$h/conf/trunk/shlomif-settings/bash-aliases/common_aliases.bash",
    "$h/.common_aliases.bash" );
