#!/usr/bin/env perl

use strict;
use warnings;

use File::Spec;
use File::Basename;

my $conf_dir = File::Spec->rel2abs(dirname($0));
my $h = $ENV{HOME};

my $rel_path = $conf_dir;
$rel_path =~ s{\A\Q$h\E/}{};

symlink("$rel_path/dot-dzil", "$h/.dzil");
